### ISSUE TITLE
two profiles installed for Plone 5.1.0.1

### ISSUE THREAD

**Issue by rileydog** [collective/collective.contentrules.comingsoon#2]
installing per usual, get the following issues:  1) two installations shown; 2) a "can't be uninstalled" but your notes said you changed to allow un install.
![screenshot 21](https://user-images.githubusercontent.com/1693063/37931603-0e48404e-30fb-11e8-91b6-4646730c12b6.png)

**Comment by rodfersou** [comment]
This is not happening here, going to close this issue, if the problem persists, please open it again.
